services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    restart: always

  service-client:
    build: ./client
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul

  service-car:
    build: ./car
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul

  gateway:
    build: ./gateway
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul
